config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'project-play' => 'home#projectplay', as: 'projectplay'

  get 'tos' => 'home#termsandconditions', as: 'tos'
  get 'genqr' => 'home#generateqr'
  get 'trendsgame' => 'home#game', as: 'game'
  post 'home/activate/:id' => 'home#activate'

  get 'tickets_day1' => 'tickets#adult_day_one'

  get 'tickets_day2' => 'tickets#adult_day_two'

  get 'tickets_season' => 'tickets#adult_season'

  get 'tickets_season_student' => 'tickets#student_season'


  get 'tickets_student_day1' => 'tickets#student_day1'

  get 'tickets_student_day2' => 'tickets#student_day2'

  get 'tickets_vip' => 'tickets#vip_tickets'

  get 'tickets_bob' => 'tickets#bob_tickets'

  get 'checkticket/:code' => 'tickets#ticket_check'

  get 'validateticket/:code' => 'tickets#ticket_verify'


  resources :tickets, only: [:create, :new, :index]

  # get 'driftgame' => 'home#casino'
  # get 'importtickets' => 'tickets#import', as: 'import_get'
  post 'importtickets' => 'tickets#import', as: 'import'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'game', only: [:game]

  def index
  end

  def termsandconditions
  end

  def casino
    render layout: 'casino'
  end

  def projectplay
    render layout: 'empty'
  end

  def game
    if user_signed_in?
    gon.user = current_user.id
    end
  end

  def activate
    @user = User.find(params[:id])

    if @user.update(active: params[:active])
      render json: {
          success: 'OK',
          message: 'Your did not win'
      }
    else
      render json: {
          error_message: @user.errors.full_messages
      }
    end
  end
    private
      def user_params
        params.require(:user).permit(:active)
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/casino.html.erb
<h1>This is the casino page.</h1>


<div class="slotmachine" >
  <div class="slotmachine__elements" id="machine">

    <div id="casino1" class="slotMachine">
      <div class="slotmachine__elements--slot1"></div>
      <div class="slotmachine__elements--slot2"></div>
      <div class="slotmachine__elements--slot3"></div>
      <div class="slotmachine__elements--slot4"></div>
      <div class="slotmachine__elements--slot5"></div>
      <div class="slotmachine__elements--slot6"></div>
    </div>

    <div id="casino2" class="slotMachine">
      <div class="slotmachine__elements--slot1"></div>
      <div class="slotmachine__elements--slot2"></div>
      <div class="slotmachine__elements--slot3"></div>
      <div class="slotmachine__elements--slot4"></div>
      <div class="slotmachine__elements--slot5"></div>
      <div class="slotmachine__elements--slot6"></div>
    </div>

    <div id="casino3" class="slotMachine">
      <div class="slotmachine__elements--slot1"></div>
      <div class="slotmachine__elements--slot2"></div>
      <div class="slotmachine__elements--slot3"></div>
      <div class="slotmachine__elements--slot4"></div>
      <div class="slotmachine__elements--slot5"></div>
      <div class="slotmachine__elements--slot6"></div>
    </div>


  </div>
  <div class="slotmachine__buttons">
    <button class="slotmachine__buttons__button slotmachine__buttons__button--start" id="casinoShuffle">Start</button>
    <button class="slotmachine__buttons__button slotmachine__buttons__button--stop" id="casinoStop">Stop</button>
  </div>
</div>

app/views/home/game.html.erb
<div  >
  <div id="particles-js"></div>

  <div class="content">

      <%= image_tag 'game/jackpotbanner.png', class: 'banner' %>
    
    <h1 class="title">WIN A FREE DRIFT PASS</h1>
    <div class="game-container">
      <div id="casino1" class="slotMachine" style="margin-left: -65px;">
        <div class="slot slot1"></div>
        <div class="slot slot2"></div>
        <div class="slot slot3"></div>
        <div class="slot slot4"></div>
        <div class="slot slot5"></div>
        <div class="slot slot6"></div>
      </div>


      <div id="casino2" class="slotMachine">
        <div class="slot slot1"></div>
        <div class="slot slot2"></div>
        <div class="slot slot3"></div>
        <div class="slot slot4"></div>
        <div class="slot slot5"></div>
        <div class="slot slot6"></div>
      </div>

      <div id="casino3" class="slotMachine">
        <div class="slot slot1"></div>
        <div class="slot slot2"></div>
        <div class="slot slot3"></div>
        <div class="slot slot4"></div>
        <div class="slot slot5"></div>
        <div class="slot slot6"></div>
      </div>
    </div>

    <div class="  btn-group " role="group" >

      <% if user_signed_in?  %>

        <% if current_user.active === true  %>

          <button id="casinoShuffle" type="button" class="btn btn--shuffle">Shuffle!</button>
          <button id="casinoStop" type="button" class="btn btn--stop">Stop!</button>

          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn--logout'%>
        <% else %>


          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-lg' %>
        <% end %>

      <% else current_user %>
        <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path,  class: 'btn btn-primary fb' %>
      <% end %>

    </div>

    <h2>
      <% if user_signed_in? %>
        <%if  current_user.active === true%>
          Hello <strong> <%= current_user.name %></strong> try and win a free ticket! Click on Shuffle to start rolling the machine!

        <% else %>
          Sorry <strong> <%= current_user.name %> </strong>,You did not win!
        <% end %>

      <% else %>
        Get lucky and earn free ticket
      <%end %>
    </h2>

  </div>

</div>

app/views/home/generateqr.html.erb
<%#= raw @image %>

app/views/home/index.html.erb
<div class="container">

  <nav>
    <ul>
      <li><%= link_to 'Win FREE Passes', game_path %></li>
      <li><a href="#artists">Artists</a></li>
      <li><a href="https://in.bookmyshow.com/events/the-drift-sounds-of-tomorrow/ET00095651" target="_blank">Passes</a></li>
      <li><a href="#" data-toggle="modal" data-target="#exampleModal">Contact Us</a></li>
    </ul>
  </nav>

  <div id="particles-js"></div>

</div>


<header>
  <%= image_tag 'trendslogo.png', class: 'trends-logo' %>
  <div class="logo"></div>
  <div class="dates">
    <p>MARCH</p>
    <p class="date">9 - 10</p>
    <p>2019</p>
  </div>

  <a href="https://in.bookmyshow.com/events/the-drift-sounds-of-tomorrow/ET00095651" target="_blank" class="btn btn-4 btn-4a icon-arrow-right">BUY TICKETS</a>
</header>



<section class="section-1">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 left-side col-sm-12">
        <%= image_tag 'pplay.png', class: 'pplaylogo' %>

        <h2>BATTLE OF THE BANDS</h2>
        <hr class="hr">
        <p>Battle it out with the best bands in the North-East!</p>
        <p style="padding-bottom: 25px;">Perform at the Drift Music Festival and  win the grand prize!</p>



      </div>

      <div class="col-lg-6">
        <%= image_tag 'bobasset.png', class: 'bobasset  d-none d-sm-block' %>
      </div>
    </div>
  </div>
</section>


<section class="artists" id="artists">
  <div class="container">
    <h2>The artists</h2>
    <hr class="hr">


    <div class="bands">
      <%= image_tag 'bands/ritviz.jpg' %>
      <%= image_tag 'bands/gurbax.jpg' %>
      <%= image_tag 'bands/wcmt.jpg' %>
      <%= image_tag 'bands/awks.jpg' %>
      <%= image_tag 'bands/sankuraj.jpg' %>
      <%= image_tag 'bands/smatt.jpg' %>
      <%= image_tag 'bands/tranceeffect.jpg' %>
      <%= image_tag 'bands/lateral.jpg' %>
      <%= image_tag 'bands/yellowdiary.jpg' %>
      </div>

  </div>
</section>

<section class="terminal-design"></section>



<section class="artists" id="artists">
  <div class="container">
    <h2>Our Partners</h2>
    <hr class="hr">


    <div class="owl-carousel owl-theme mt-3rem">
      <div class="dummy"><%= image_tag 'sponsors/titlesponsor.jpg' %></div>
      <div class="dummy"><%= image_tag 'sponsors/sponsor1.jpg' %></div>
      <div class="dummy"><%= image_tag 'sponsors/sterling.jpg' %></div>
      <div class="dummy"><%= image_tag 'sponsors/gplus.jpg' %></div>
      <div class="dummy"><%= image_tag 'sponsors/em.jpg' %></div>
      <div class="dummy"><%= image_tag 'sponsors/sponsor4.jpg' %></div>

    </div>
  </div>
</section>

<section class="terminal-design"></section>

<footer>

</footer>

<div class="footersection">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= image_tag 'logo.png', class: 'footer-logo' %>
      </div>

      <div class="col-md-3 newsletter-section">
        <%= image_tag 'tunein.png', class: 'tuneinlogo' %>
        <a href="#" class="btn-newsletter">Join the newsletter</a>
      </div>

      <div class="col-md-3">
        <ul>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms of use</a></li>
          <li><a href="#">Web Accessibility</a></li>
          <li><a href="#">Wrist Band Usage</a></li>
        </ul>
      </div>

      <div class="col-md-3">
        <ul>
          <li><a href="#">Sponsors</a></li>
          <li><a href="#">Charity</a></li>
          <li><a href="#">Accessibility</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">CONTACT US</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/home/projectplay.html.erb
<div class="typeform-widget" data-url="https://nilotpal1.typeform.com/to/o16HwS" style="width: 100%; height: 100%;"></div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"> powered by <a href="https://admin.typeform.com/signup?utm_campaign=o16HwS&utm_source=typeform.com-13261345-Basic&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN" style="color: #999" target="_blank">Typeform</a> </div>

app/views/home/termsandconditions.html.erb
<div class="container">
  <div class="text-center tos">
    <h1>Music Release Form</h1>
  <p> I hereby acknowledge my participation in the Drift Festival and give full authority to the promoters at Superpress use my submitted music/video as heard within the audition piece and grant all rights to said promoters to use such recordings, in whole or in part for promotional use on the festival’s social accounts with attribution. I also acknowledge that all music/video content is original in nature and I own the sole and legal copyright to described work, and hereby agree to the use of this work for promotional purposes.</p>


    <h2>Rules and Regulations</h2>
    <h3>Only Live Music!</h3>

    <ol style="text-align: left">
      <li>Each band has to get its own instruments. Only a common drum kit will be
        provided.</li>

      <li>Sequencing will NOT be allowed. It will result in the band being disqualified.</li>


      <li>No alcohol will be allowed on stage while performing.</li>

      <li>The organisers would like to request all participants to please leave their religious
        affiliations at home when they come to perform.</li>

      <li>Inability to follow the above rule will lead to disqualification.</li>

      <li>Each band will have to submit the lyrics of their original song as a typed sheet.
        Please do not scrawl it out on a piece of paper at the last minute and present to the
        judges. Our judges are music experts- not handwriting analysts. If you have 2-3
        original scores and plan to decide which to perform only at the venue (For
        instance: after seeing what others have performed) then we recommend that you
        carry along the typed lyrics for all of them.</li>


      <li>All participating Bands must give the organisers a brief write up on themselves.
        This should include 1 or 2 pictures, list of members and what they play, any
        interesting facts like: when they began, their inspirations, favourite bands, the
        kind of music they will perform, competitions won etc. We require this for
        newspaper write ups. Please keep this ready and give it to us along with your
        participation form- as it becomes difficult for us to follow up on each band for the
        info.</li>

    </ol>


    <h2>Format of the competition</h2>

    <ol style="text-align: left">
      <li>The show starts at 10.00.a.m. sharp. Reporting time will be 9. a.m.</li>

      <li>Each of the bands will have to perform 3 songs each. It will be 1
        original composition which will be compulsory. The balance numbers
        can belong to any category of music- Rock, POP, Jazz, Fusion, Folk,
        Alternative, Metal or any other genre.</li>


      <li>There will be only 1 winning band. The winner takes it all.</li>



    </ol>
  </div>




  <%= link_to 'Back', projectplay_path %>
</div>