config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'project-play' => 'home#projectplay', as: 'projectplay'

  get 'tos' => 'home#termsandconditions', as: 'tos'
  get 'genqr' => 'home#generateqr'
  get 'trendsgame' => 'home#game', as: 'game'
  post 'home/activate/:id' => 'home#activate'

  get 'tickets_day1' => 'tickets#adult_day_one'

  get 'tickets_day2' => 'tickets#adult_day_two'

  get 'tickets_season' => 'tickets#adult_season'

  get 'tickets_season_student' => 'tickets#student_season'


  get 'tickets_student_day1' => 'tickets#student_day1'

  get 'tickets_student_day2' => 'tickets#student_day2'

  get 'tickets_vip' => 'tickets#vip_tickets'

  get 'tickets_bob' => 'tickets#bob_tickets'

  get 'checkticket/:code' => 'tickets#ticket_check'

  get 'validateticket/:code' => 'tickets#ticket_verify'


  resources :tickets, only: [:create, :new, :index]

  # get 'driftgame' => 'home#casino'
  # get 'importtickets' => 'tickets#import', as: 'import_get'
  post 'importtickets' => 'tickets#import', as: 'import'
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id                :bigint(8)        not null, primary key
#  random_code       :string(255)
#  user_listed       :string(255)
#  qr_code           :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  ticket_type       :integer
#  number_of_tickets :integer
#  student           :integer
#

require 'csv'

class Ticket < ApplicationRecord

  TICKET_TYPE = {
      1 => 'DAY 1',
      2 => 'DAY 2',
      3 => 'SEASON PASS',
      4 => 'FREE PASS',
      5 => 'VIP',
      6 => 'BOB' # Battle Of Bands
  }.freeze

  STUDENT = {
      1 => 'NON - STUDENT',
      2 => 'STUDENT'
  }.freeze

  # So that all the values that get generated is random
  validates :random_code, uniqueness: true

  validates :user_listed, :ticket_type, :student, presence: true

  mount_base64_uploader :qr_code, QrCodeUploader
  after_create :update_generate_code

  # This is for the importing of the CSV to the web app.
  def self.import_csv(file)
    items = []
    CSV.foreach(file.path, headers: true) do |row|
      items << Ticket.new(row.to_h)
    end
    Ticket.import(items)
  end

  def self.to_csv
    attributes = %w{id random_code user_listed ticket_type student checked}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  def update_generate_code
    base_64_image = RQRCode::QRCode.new(self.random_code).as_png(
         size: 280
    ).to_data_url
    self.qr_code = base_64_image
    self.save!
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [:ticket_check, :ticket_verify, :index, :import, :new, :create]

  def index
    @tickets = Ticket.all
    respond_to do |format|
      format.html
      format.csv { send_data @tickets.to_csv, filename: "tickets-#{Date.today}.csv" }
    end
  end

  def import
    Ticket.import_csv(params[:file])
    redirect_to tickets_path, notice: 'Data imported successfully.'
  end

  def ticket_check
  #   Create Checked
  #   Check if the ticket exists.
  #     Check the "checked parameter"
  #      if it is set to false or null set "Checked" to true and the then send message: "The ticket has been checked and validated" , code: 1
  #     If is is set to true then message: "Ticket already scanned. Duplicate Ticket", code : 2
  #  ELSE send message : "Ticket DOES NOT EXIT. FAKE Ticket!", code : 3
  #
    if params[:code].empty?
      render json: {
          code: 404,
          message: 'No PARAMS detected'
      }
    end
    ticket_code = params[:code]
    ticket = Ticket.find_by(random_code: ticket_code)

    if ticket.present?
      if ticket.checked
        render json: {
            code: 2,
            message: 'Ticket already scanned. DUPLICATE Ticket'
        }
      else
          ticket.update!(checked: true)
         render json: {
             code: 1,
             message: 'The ticket has been checked and validated.'
         }
      end

    else
      render json: {
          code: 3,
          message: 'FAKE TICKET! Ticket does not exist!'
      }
    end

  end


  def ticket_verify
    # This is the code to verify if the ticket is valid. And has been checked properly.
      if params[:code].empty?
        render json: {
            code: 404,
            message: 'No PARAMS detected'
        }
      end
      ticket_code = params[:code]
      ticket = Ticket.find_by(random_code: ticket_code)
  
      if ticket.present?
        if ticket.checked
          render json: {
              code: 4,
              message: 'Valid Ticket'
          }
        else
            # ticket.update!(checked: true)
           render json: {
               code: 5,
               message: 'INVALID TICKET'
           }
        end
  
      else
        render json: {
            code: 3,
            message: 'FAKE TICKET! Ticket does not exist!'
        }
      end
  
    end

  def vip_tickets
    @tickets = Ticket.where(ticket_type: 5)
  end

  def bob_tickets
    @tickets = Ticket.where(ticket_type: 6)
  end

  def adult_day_one
    @tickets = Ticket.where("ticket_type = 1 and student = 1")
  end

  # Total gen : 800, Checked : 798
  def adult_day_two
    @tickets = Ticket.where("ticket_type = 2 and student = 1")
  end

  # Gen: 1110, Checked : 1100
  def adult_season
    @tickets = Ticket.where("ticket_type = 3 and student = 1")
  end

  # Gen 800, Checked : 733
  def student_day1
    @tickets = Ticket.where(["ticket_type = 1 and student = 2"])
  end

  # Gen: 1500, Print: 1200, Checked: 1188
  def student_season
    @tickets = Ticket.where(["ticket_type = 3 and student = 2"]).limit(1200)
  end

  #  Gen 800, Checked : 790
  def student_day2
    @tickets = Ticket.where(["ticket_type = 2 and student = 2"])
  end

  #  Total printed tickets: 5510
  #   Total checked: 5207
  # False tickets : 303

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(set_params)

    if @ticket.number_of_tickets > 0
      @ticket.number_of_tickets.times do
        Ticket.create!(random_code: ('a'..'z').to_a.shuffle[0,12].join, student: @ticket.student, ticket_type: @ticket.ticket_type, user_listed: @ticket.user_listed)
      end
    end
    redirect_to tickets_path, notice: 'The tickets have been generated'

  end


  private

  def set_params
    params.require(:ticket).permit(:user_listed, :student, :number_of_tickets, :ticket_type)
  end
end

app/views/tickets/adult_day_one.html.erb
<% if @tickets.present? %>

    <% @tickets.each do |ticket| %>
      <%= image_tag ticket.qr_code.url(:day1), class: 'festival-ticket' %>
      <%#= ticket.random_code %>
    <% end %>

<% end %>

app/views/tickets/adult_day_two.html.erb
<% if @tickets.present? %>

  <% @tickets.each do |ticket| %>
    <%= image_tag ticket.qr_code.url(:day2), class: 'festival-ticket' %>
    <%#= ticket.random_code %>
  <% end %>

<% end %>

app/views/tickets/adult_season.html.erb
<% if @tickets.present? %>

  <% @tickets.each do |ticket| %>
    <%= image_tag ticket.qr_code.url(:maketicket_season), class: 'festival-ticket' %>
    <%#= ticket.random_code %>
  <% end %>

<% end %>

app/views/tickets/bob_tickets.html.erb
<% if @tickets.present? %>

  <% @tickets.each do |ticket| %>
    <%= image_tag ticket.qr_code.url(:bob), class: 'festival-ticket' %>
    <%#= ticket.random_code %>
  <% end %>

<% end %>

app/views/tickets/import.html.erb
<%= form_tag import_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>

app/views/tickets/index.html.erb
<div class="container">

<h1>Hello</h1>

</div>

<%= form_tag import_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>

app/views/tickets/new.html.erb
<div class="container">
  <div class="ticket-form">
    <%= simple_form_for(@ticket) do |f| %>

      <%= f.input :user_listed, label: 'User Responsibility' %>
      <%= f.input :ticket_type, :collection => Ticket::TICKET_TYPE.sort.map {|k,v| [v,k]} %>
      <%= f.input :student, :collection => Ticket::STUDENT.sort.map {|k,v| [v,k]}  %>
      <%= f.input :number_of_tickets %>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/tickets/student_day1.html.erb
<% if @tickets.present? %>

  <% @tickets.each do |ticket| %>
    <%= image_tag ticket.qr_code.url(:day1_student), class: 'festival-ticket' %>
    <%#= ticket.random_code %>
  <% end %>

<% end %>

app/views/tickets/student_day2.html.erb
<% if @tickets.present? %>

  <% @tickets.each do |ticket| %>
    <%= image_tag ticket.qr_code.url(:day2_student), class: 'festival-ticket' %>
    <%#= ticket.random_code %>
  <% end %>

<% end %>

app/views/tickets/student_season.html.erb
<% if @tickets.present? %>

  <% @tickets.each do |ticket| %>
    <%= image_tag ticket.qr_code.url(:maketicket_season_student), class: 'festival-ticket' %>
    <%#= ticket.random_code %>
  <% end %>

<% end %>

app/views/tickets/vip_tickets.html.erb
<% if @tickets.present? %>

  <% @tickets.each do |ticket| %>
    <%= image_tag ticket.qr_code.url(:vip), class: 'festival-ticket' %>
    <%#= ticket.random_code %>
  <% end %>

<% end %>